# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job:
  displayName: Windows
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      64-bit Debug:
        BuildType: Debug
        CMakeArgs: '-G "Visual Studio 16 2019" -A x64'
      64-bit Release:
        BuildType: Release
        CMakeArgs: '-G "Visual Studio 16 2019" -A x64'
      32-bit Debug:
        BuildType: Debug
        CMakeArgs: '-G "Visual Studio 16 2019" -A Win32'
      32-bit Release:
        BuildType: Release
        CMakeArgs: '-G "Visual Studio 16 2019" -A Win32'
  steps:
  - checkout: self
    submodules: true
  - task: CMake@1
    displayName: 'CMake .. $(CMakeArgs) -DCMAKE_BUILD_TYPE=$(BuildType)'
    inputs:
      cmakeArgs: '.. $(CMakeArgs) -DCMAKE_BUILD_TYPE=$(BuildType)'
  - task: CMake@1
    displayName: 'CMake --build . --config $(BuildType)'
    inputs:
      cmakeArgs: '--build . --config $(BuildType)'

