# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job:
  displayName: Windows
  pool:
    vmImage: 'windows-2019'
  strategy:
    matrix:
      64-bit Debug:
        BuildConfiguration: Debug
        CMakeArgs: '-G "Visual Studio 16 2019" -A x64'
      64-bit Release:
        BuildConfiguration: Release
        CMakeArgs: '-G "Visual Studio 16 2019" -A x64'
      32-bit Debug:
        BuildConfiguration: Debug
        CMakeArgs: '-G "Visual Studio 16 2019" -A Win32'
      32-bit Release:
        BuildConfiguration: Release
        CMakeArgs: '-G "Visual Studio 16 2019" -A Win32'
  steps:
  - checkout: self
    submodules: true
  - task: CMake@1
    displayName: 'cmake configure'
    inputs:
      cmakeArgs: '.. $(CMakeArgs)'
  - task: CMake@1
    displayName: 'build'
    inputs:
      cmakeArgs: '--build . --config $(BuildConfiguration)'
  - task: CopyFiles@2
    displayName: 'copy files'
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: '**/$(BuildConfiguration)/**/?(*.exe|*.dll|*.pdb)'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
  - task: PublishBuildArtifacts@1
    displayName: 'publish artifacts'
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: drop

