name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [Win32, x64]
        buildType: [Release, Debug]
        generator: [Visual Studio 16 2019]
        os: [windows-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        path: src
        submodules: recursive
    - name: CMake build
      shell: powershell
      run: |
        New-Item -Name build -ItemType directory | Out-Null
        cmake -G "${{ matrix.generator }}" -A ${{ matrix.arch }} -S src -B build
        cmake --build build --config ${{ matrix.buildType }}
        New-Item -Name out -ItemType directory | Out-Null
        Copy-Item "build/${{ matrix.buildType }}/version.dll" -Destination "out" | Out-Null
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: shugoconsoledll-${{ matrix.arch }}-${{ matrix.buildType }}
        path: out
        
