name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [Win32, x64]
        buildType: [Release, Debug]
        generator: [Visual Studio 16 2019]
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: cmake build
      uses: lukka/run-cmake@v0.11
      with:
        cmakeBuildType: ${{ matrix.buildType }}
        cmakeGenerator: ${{ matrix.generator }}
        cmakeAppendedArgs: -A ${{ matrix.arch }}
        buildDirectory: ${{ github.workspace }}/build
