name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        arch: [Win32, x64]
        buildType: [Release, Debug]
        generator: [Visual Studio 16 2019]
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v2
      with:
        path: src
        submodules: recursive
    - name: cmake build
      shell: powershell
      run: |
        New-Item -Name build -ItemType directory | Out-Null
        cmake -G "${{ matrix.generator }}" -A ${{ matrix.arch }} -S src -B build
        cmake --build build
        
